version: '3'
services:

  fhir-proxy:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  loadtest:
    image: grafana/k6:latest
    volumes:
      - ./tests/load:/tests
    command: run /tests/healthcheck.js
    depends_on:
      - fhir-proxy
